## Pandas Read CSV in Python

CSV files are the Comma Separated Files that allow storage of tabular data.

- To access data from the CSV file, we require a function read_csv() from Pandas that retrieves data in the form of the data frame.
- First, we must import the Pandas library, then using Pandas load this data into a DataFrame

In [7]:
import pandas as pd

df = pd.read_csv("../Dataset/people_data.csv")
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

### read_csv() function
read_csv() function in Pandas is used to read data from CSV files into a Pandas DataFrame. A DataFrame is a data structure that allows you to manipulate and analyze tabular data efficiently. CSV files are plain-text files where each row represents a record, and columns are separated by commas (or other delimiters).

#### Syntax
pd.read_csv(filepath_or_buffer, sep=' ,' , header='infer',  index_col=None, usecols=None, engine=None, skiprows=None, nrows=None) 

##### Parameters:

- filepath_or_buffer: Location of the csv file. It accepts any string path or URL of the file.
- sep: It stands for separator, default is ', '.
- header: It accepts int, a list of int, row numbers to use as the column names, and the start of the data. If no names are passed, i.e., header=None, then, it will display the first column as 0, the second as 1, and so on.
- usecols: Retrieves only selected columns from the CSV file.
- nrows: Number of rows to be displayed from the dataset.
- index_col: If None, there are no index numbers displayed along with records.  
- skiprows: Skips passed rows in the new data frame.

### Features in Pandas read_csv

#### 1. Read specific columns using read_csv
The usecols parameter allows to load only specific columns from a CSV file. This reduces memory usage and processing time by importing only the required data.

In [9]:
df = pd.read_csv("../Dataset/people_data.csv", usecols=["First Name", "Email"])
print(df)

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

#### 2. Setting an Index Column (index_col)
The index_col parameter sets one or more columns as the DataFrame index, making the specified column(s) act as row labels for easier data referencing.

In [10]:
df = pd.read_csv("../Dataset/people_data.csv", index_col="First Name")
print(df)

           Last Name     Sex                       Email Date of birth  \
First Name
Shelby       Terrell    Male        elijah57@example.net    1945-10-26
Phillip      Summers  Female       bethany14@example.com    1910-03-24
Kristine      Travis    Male       bthompson@example.com    1992-07-02
Yesenia     Martinez    Male   kaitlinkaiser@example.com    2017-08-03
Lori            Todd    Male  buchananmanuel@example.net    1938-12-01

                     Job Title
First Name
Shelby         Games developer
Phillip         Phytotherapist
Kristine             Homeopath
Yesenia      Market researcher
Lori        Veterinary surgeon

#### 3. Handling Missing Values Using read_csv
The na_values parameter replaces specified strings (e.g., "N/A", "Unknown") with NaN, enabling consistent handling of missing or incomplete data during analysis.\

In [12]:
df = pd.read_csv("../Dataset/people_data.csv", na_values=["N/A", "Unknown"])
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

#### 4. Reading CSV Files with Different Delimiters
In this example, we will take a CSV file and then add some special characters to see how the sep parameter works.

In [ ]:
import pandas as pd

data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

with open("sample.csv", "w") as file:
    file.write(data)
print(data)

#### 6. Using skiprows in read_csv()
The skiprows parameter skips unnecessary rows at the start of a file, which is useful for ignoring metadata or extra headers that are not part of the dataset.

In [13]:
df = pd.read_csv("../Dataset/people_data.csv", skiprows = [4,5])
print("Dataset After skipping rows: ")
print(df)

Dataset After skipping rows:
  First Name Last Name     Sex                  Email Date of birth  \
0     Shelby   Terrell    Male   elijah57@example.net    1945-10-26
1    Phillip   Summers  Female  bethany14@example.com    1910-03-24
2   Kristine    Travis    Male  bthompson@example.com    1992-07-02

         Job Title
0  Games developer
1   Phytotherapist
2        Homeopath

#### 7. Loading a CSV Data from a URL
Pandas allows you to directly read a CSV file hosted on the internet using the file's URL. This can be incredibly useful when working with datasets shared on websites, cloud storage, or public repositories like GitHub.

In [ ]:
url = "https://media.geeksforgeeks.org/wp-content/uploads/20241121154629307916/people_data.csv"
df = pd.read_csv(url)
df