## Working with Missing Data in Pandas

In Pandas, missing data occurs when some values are missing or not collected properly and these missing values are represented as:

- None: A Python object used to represent missing values in object-type arrays.
- NaN: A special floating-point value from NumPy which is recognized by all systems that use IEEE floating-point standards.

### Difference between None and NaN
Both None and NaN represent missing values, but they are not exactly the same.
1) None
- None is a Python built-in object.
- It means: “no value” / “nothing”
- example:

x = None
print(x)
print(type(x))
- output: None and <class 'NoneType'>


2) NaN
- NaN means: Not a Number
- It is mainly used for numeric missing values.
- In pandas / NumPy it usually appears as:

import numpy as np

x = np.nan
print(x)
print(type(x))

- Output: nan and <class 'float'>  So NaN is actually a float value.


##### Most important difference
- None → Python missing object
- NaN → numeric missing value (float)

### Checking Missing Values in Pandas
Pandas provides two important functions which help in detecting whether a value is NaN helpful in making data cleaning and preprocessing easier in a DataFrame or Series are given below :

#### 1. Using isnull()
isnull() returns a DataFrame of Boolean value where True represents missing data (NaN). This is simple if we want to find and fill missing data in a dataset.

Example 1: Finding Missing Values in a DataFrame

We will be using Numpy and Pandas libraries for this implementation.

In [1]:
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

mv = df.isnull()

print(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

#### Example 2: Filtering Data Based on Missing Values

Here we used random Employee dataset. The isnull() function is used over the "Gender" column in order to filter and print out rows containing missing gender data.

In [2]:
import pandas as pd
d = pd.read_csv("../Dataset/employees.csv")

bool_series = pd.isnull(d["Gender"])
missing_gender_data = d[bool_series]
print(missing_gender_data)

    First Name Gender  Start Date Last Login Time  Salary  Bonus %  \
20        Lois    NaN   4/22/1995         7:18 PM   64714    4.934
22      Joshua    NaN    3/8/2012         1:58 AM   90816   18.816
27       Scott    NaN   7/11/1991         6:58 PM  122367    5.218
31       Joyce    NaN   2/20/2005         2:40 PM   88657   12.752
41   Christine    NaN   6/28/2015         1:08 AM   66582   11.308
..         ...    ...         ...             ...     ...      ...
961    Antonio    NaN   6/18/1989         9:37 PM  103050    3.050
972     Victor    NaN   7/28/2006         2:49 PM   76381   11.159
985    Stephen    NaN   7/10/1983         8:10 PM   85668    1.909
989     Justin    NaN   2/10/1991         4:58 PM   38344    3.794
995      Henry    NaN  11/23/2014         6:09 AM  132483   16.655

    Senior Management                  Team
20               True                 Legal
22               True       Client Services
27              False                 Legal
31              False               Product
41               True  Business Development
..                ...                   ...
961             False                 Legal
972              True                 Sales
985             False                 Legal
989             False                 Legal
995             False          Distribution

[145 rows x 8 columns]

### 2. Using isna()
isna() returns a DataFrame of Boolean values where True indicates missing data (NaN). It is used to detect missing values just like isnull().

Example: Finding Missing Values in a DataFrame

In [3]:
import pandas as pd
import numpy as np

data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)

# Check for missing values using isna()
print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

### Difference between isnull() and isna()

- No actual difference in functionality: isnull() and isna() both check for missing values in a pandas DataFrame or Series.
- Same output: Both return a boolean result where:
- - True → value is missing (NaN, None, NaT)
- - False → value is present
- isnull(): Older and more SQL-style naming convention.
- isna(): Newer and more modern naming style, aligned with NumPy’s isnan() naming.
- Internally same: Both methods use the same underlying pandas logic, so there is no performance difference.
- Best practice: Most developers prefer isna() because it is shorter and more readable.

### 3. Checking for Non-Missing Values Using notnull()
notnull() function returns a DataFrame with Boolean values where True indicates non-missing (valid) data. This function is useful when we want to focus only on the rows that have valid, non-missing values.

Example 1: Identifying Non-Missing Values in a DataFrame

In [5]:
import pandas as pd
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

nmv = df.notnull()

print(nmv)

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

### Filling Missing Values in Pandas
Following functions allow us to replace missing values with a specified value or use interpolation methods to find the missing data.

1. Using fillna()
fillna() used to replace missing values (NaN) with a given value. Lets see various example for this.

Example 1: Fill Missing Values with Zero

In [6]:
import numpy as np

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

df.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

Example 2: Fill with Previous Value (Forward Fill)

The pad method is used to fill missing values with the previous value.

In [7]:
df.fillna(method='pad')

C:\Users\Swastikpc\AppData\Local\Temp\ipykernel_10228\196241153.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='pad')

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

Example 3: Fill with Next Value (Backward Fill)

The bfill function is used to fill it with the next value.

In [8]:
df.fillna(method='bfill')

C:\Users\Swastikpc\AppData\Local\Temp\ipykernel_10228\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

### Dropping Missing Values in Pandas
The dropna() function used to removes rows or columns with NaN values. It can be used to drop data based on different conditions.

#### 1. Dropping Rows with At Least One Null Value
- Remove rows that contain at least one missing value.

In [9]:
import pandas as pd
import numpy as np

dict = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, 40, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

df.dropna()

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

#### 2. Dropping Rows with All Null Values
- We can drop rows where all values are missing using dropna(how='all').

In [10]:
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

df.dropna(how='all')

   First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0         52.0           NaN
2          NaN          45.0         80.0           NaN
3         95.0          56.0         98.0          65.0

#### 3. Dropping Columns with At Least One Null Value
- To remove columns that contain at least one missing value we use dropna(axis=1).

In [11]:
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [60, 67, 68, 65]}
df = pd.DataFrame(dict)

df.dropna(axis=1)

   Fourth Score
0            60
1            67
2            68
3            65

#### 4. Dropping Rows with Missing Values in CSV Files
When working with CSV files, we can drop rows with missing values using dropna().

In [13]:
import pandas as pd
d = pd.read_csv("../Dataset/employees.csv")

nd = d.dropna(axis=0, how='any')

print("Old data frame length:", len(d))
print("New data frame length:", len(nd))
print("Rows with at least one missing value:", (len(d) - len(nd)))

Old data frame length: 1000
New data frame length: 764
Rows with at least one missing value: 236