## Filter Pandas Dataframe with multiple conditions

### Filter Pandas Dataframe with multiple conditions
The reason is dataframe may be having multiple columns and multiple rows. Selective display of columns with limited rows is always the expected view of users. To fulfill the user's expectations and also help in machine deep learning scenarios, filtering of Pandas dataframe with multiple conditions is much necessary.

In [7]:
# import module
import pandas as pd
import numpy as np
# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          
                          'Age': [30, 35, 37, 33, 34, 30],
                          
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# display dataframe
display(dataFrame)

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

### Filter Pandas Dataframe with multiple conditions Using loc
Here we will get all rows having Salary greater or equal to 100000 and Age < 40 and their JOB starts with ‘D’ from the dataframe. Print the details with Name and their JOB. For the above requirement, we can achieve this by using loc. It is used to access single or more rows and columns by label(s) or by a boolean array. loc works with column labels and indexes.

In [2]:
# filter dataframe
display(dataFrame.loc[(dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')),
                    ['Name','JOB']])

        Name       JOB
0   RACHEL    DESIGNER

In [6]:
dataFrame.loc[(dataFrame['Age'] >= 35) & (dataFrame['Salary'] < 100000)]

        Name  Age  Salary    JOB
1   MONICA     35   93000   CHEF
2   PHOEBE     37   88000  MASUS

### Filter Pandas Dataframe Using NumPy
Here will get all rows having Salary greater or equal to 100000 and Age < 40 and their JOB starts with ‘D’ from the data frame. We need to use NumPy.

In [8]:
# filter dataframe                                   
filtered_values = np.where((dataFrame['Salary']>=100000) & (dataFrame['Age']< 40) & (dataFrame['JOB'].str.startswith('D')))
print(filtered_values)
display(dataFrame.loc[filtered_values])

(array([0], dtype=int64),)

        Name  Age  Salary       JOB
0   RACHEL     30  100000  DESIGNER

In the above example, print(filtered_values) will give the output as (array([0], dtype=int64),)  which indicates the first row with index value 0 will be the output. After that output will have 1 row with all the columns and it is retrieved as per the given conditions.

### Filter Pandas Dataframe Using Query (eval and query works only with columns)
In this approach, we get all rows having Salary lesser or equal to 100000 and Age < 40, and their JOB starts with ‘C’ from the dataframe. Its just query the columns of a DataFrame with a single or more Boolean expressions and if multiple, it is having & condition in the middle.

In [9]:
# filter dataframe 
display(dataFrame.query('Salary  <= 100000 & Age < 40 & JOB.str.startswith("C").values'))

        Name  Age  Salary   JOB
1   MONICA     35   93000  CHEF

### Pandas Boolean indexing multiple conditions standard way ("Boolean indexing" works with values in a column only)
In this approach, we get all rows having Salary lesser or equal to 100000 and Age < 40 and their JOB starts with ‘P’ from the dataframe. In order to select the subset of data using the values in the dataframe and applying Boolean conditions, we need to follow these ways

In [10]:
# filter dataframe 
display(dataFrame[(dataFrame['Salary']>=100000) & (dataFrame['Age']<40) & dataFrame['JOB'].str.startswith('P')][['Name','Age','Salary']])

         Name  Age  Salary
3    ROSS       33  120000