## How to Create a Pivot Table in Python using Pandas?
A pivot table is a statistical table that summarizes a substantial table like a big dataset. It is part of data processing. This summary in pivot tables may include mean, median, sum, or other statistical terms. Pivot tables are originally associated with MS Excel but we can create a pivot table in Pandas using Python using the Pandas Dataframe pivot_table() method.

### Creating a Sample DataFrame

In [1]:
# importing pandas
import pandas as pd

# creating dataframe
df = pd.DataFrame({'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                               'Beans', 'Orange', 'Broccoli', 'Banana'],
                   'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                                'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
                   'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
                   'Amount': [270, 239, 617, 384, 626, 610, 62, 90]})
df

    Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

### Create a Pivot Table in Pandas

#### Example 1: Get the Total Sales of Each Product
In this example, the DataFrame 'df' is transformed using a pivot table, aggregating the total 'Amount' for each unique 'Product' and displaying the result with the sum of amounts for each product.

In [3]:
pivot = df.pivot_table(index = ['Product'], values = ['Amount'], aggfunc = 'sum')
pivot

          Amount
Product
Banana      1091
Beans        626
Broccoli     301
Carrots      270
Orange       610

#### Example 2: Get the Total Sales of Each Category
In this example, a pivot table is created from the DataFrame 'df' to summarize the total 'Amount' sales for each unique 'Category,' employing the 'sum' aggregation function, and the result is printed.

In [5]:
total_sales = df.pivot_table(index = ['Category'], values = ['Amount'], aggfunc = 'sum')
total_sales

           Amount
Category
Fruit        1701
Vegetable    1197

#### Example 3: Get Total Sales by Category and Product Both
In this example, a pivot table is generated from the DataFrame 'df' to showcase the total 'Amount' sales for unique combinations of 'Product' and 'Category,' utilizing the 'sum' aggregation function. The resulting pivot table is then printed.

In [6]:
total_sales_by_c_and_p = df.pivot_table(index = ['Category', 'Product'], values = ['Amount'], aggfunc = 'sum')
total_sales_by_c_and_p

                    Amount
Category  Product
Fruit     Banana      1091
          Orange       610
Vegetable Beans        626
          Broccoli     301
          Carrots      270

#### Example 4: Get the Mean, Median, Minimum Sale by Category
In this example, a pivot table is created from the DataFrame 'df' to display the median, mean, and minimum 'Amount' values categorized by 'Category.' The aggregation functions 'median,' 'mean,' and 'min' are applied, and the resulting pivot table is printed.

In [7]:
pivot = df.pivot_table(index=['Category'], values=['Amount'],
                       aggfunc={'median', 'mean', 'min'})
print(pivot)

           Amount
             mean median min
Category
Fruit      425.25  497.0  90
Vegetable  299.25  254.5  62

#### Example 5: Get the Mean, Median, Minimum Sale by Product
In this example, a pivot table is generated from the DataFrame 'df' to showcase the median, mean, and minimum 'Amount' values for each unique 'Product.' The aggregation functions 'median,' 'mean,' and 'min' are applied, resulting in the pivot table, which is then printed.

In [8]:
pivot = df.pivot_table(index=['Product'], values=['Amount'],
                       aggfunc={'median', 'mean', 'min'})
print(pivot)

              Amount
                mean median  min
Product
Banana    363.666667  384.0   90
Beans     626.000000  626.0  626
Broccoli  150.500000  150.5   62
Carrots   270.000000  270.0  270
Orange    610.000000  610.0  610